### ISSUE TITLE
Cache commit views during runtime

### ISSUE THREAD

**Issue by sepulzera** [NinjaPewPew/CVS-History-Viewer#31]
1. Open a CVS directory with several commits.
2. Open Commit-1.
3. Open Commit-2.
4. Open Commit-1.

* Expected: The UI should switch *back* to Commit-1. Eventually further interactions, like clicking on another file of the commit, or scrolling the commit changes down, should be restored.
* Actual: Commit-1 gets loaded and the views initialized again.

-> Cache the views per commit, or cache the information to restore the view's data when changing commits.

**Comment by FaithfulDev** [comment]
Will be done.

FYI: The big table contains the commits. The list at the bottom contains the file revisions, which are belonging to the above selected commit. I understand that you want the UI to remember the revision that you selected for the previous selected commits.
