### ISSUE TITLE
General searching for a commit-id (without keyword) should give a hit

### ISSUE THREAD

**Issue by sepulzera** [NinjaPewPew/CVS-History-Viewer#35]
I can search for commits via its description. But to search for a commit-id, i have to use the keyword 'commit'. Would it be possible to search for various keywords without specifiying them? E. g., when just entering the commit id, it would still look for commits with this hash.

Of course, that should only be performed when no keyword is given.

**Comment by FaithfulDev** [comment]
To make this work, I would have to identify commit hashes beforehand, just by looking at the text box content. 

@sepulzera Do you have an idea how to do that?

**Comment by sepulzera** [comment]
First idea would be to perform a second *search for the ID*, if the input is potentially a commitID (1 word only and 6 to xxx characters) **AND** the *search for description* gives no hit.

```java
String searchInput = textbox.input;
Array<string> searchHits;

searchHits = getCommitsByDescription(searchInput);
if ( searchHits.size() == 0 
        && isOnlyOneWord(searchInput) 
        && isSizeOfACommitID(searchInput) ) {
    searchHits = getCommitsByID(searchInput);
}

displayHits(searchHits);
```

**Comment by FaithfulDev** [comment]
Doing a follow up search, if no results were found, makes a lot of sense logically. I was worried that it would be a performance issue, as searches on big datasets are currently, but in my test it worked out quite good. Let's see how it will work out in real life.
